import Tk 402.002 from CPAN
git-cpan-module:   Tk
git-cpan-version:  402.002
git-cpan-authorid: NI-S
git-cpan-file:     authors/id/N/NI/NI-S/Tk402.002.tar.gz

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -1,6 +1,32 @@
-#!/bin/sh 
-set -x
-if [ -f Makefile ] ; then make clean ; fi 
-cleanup 
-perl Makefile.PL
-time make parallel 
+#!/usr/local/bin/new/perl -w
+open(STDERR,">&STDOUT") || die "Cannot redirect STDERR";
+$| = 1;
+use Cwd;
+my $host = `uname -n`;
+chomp($host);
+my $cwd = getcwd();
+print "$host in $cwd executing $0\n";
+print $ENV{'PATH'},"\n";
+System("make","clean") if -f "Makefile";
+System("cleanup"); 
+System("$^X","Makefile.PL");
+System("time","make","parallel"); 
+
+sub System
+{
+ print join(' ',@_),"\n";
+ my $pid = fork;
+ if ($pid)
+  {
+   local %SIG;
+   $SIG{INT} = sub { warn "\nInterrupt"; kill 9,$pid; exit 1 };
+   wait;
+   die "Error $?" if ($?);
+  }
+ else
+  {
+   exec(@_) || die "Cannot exec".join(' ',@_).":$!";
+  }
+}
+
+
